version: "3.7"
services:
  postgres:
    ports:
      - "5433:5432"
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      backend:
        aliases:
          - "postgres"
  database:
    ports:
      - "5434:5432"
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: service
      POSTGRES_PASSWORD: password
    networks:
      backend:
        aliases:
          - "postgres-service"
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      backend:
        aliases:
          - "keycloak"

  keycloak-security-service:
    image:  service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/service
      SPRING_DATASOURCE_USERNAME: service
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      backend:
        aliases:
          - "keycloak-security-service"

networks:
  backend:
    driver: bridge